// ============================================
// Shared Types for NextClass
// ============================================

// Enums (will be generated by Prisma after generation)
export type UserRole = 'ADMIN' | 'INSTRUCTOR' | 'STUDENT';
export type BookingStatus = 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'COMPLETED' | 'NO_SHOW';
export type PaymentStatus = 'PENDING' | 'COMPLETED' | 'FAILED' | 'REFUNDED';
export type PaymentMethod = 'CREDIT_CARD' | 'DEBIT_CARD' | 'PAYPAL' | 'BANK_TRANSFER';
export type SessionStatus = 'SCHEDULED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
export type WaitlistStatus = 'ACTIVE' | 'NOTIFIED' | 'ENROLLED' | 'EXPIRED';
export type AuditAction = 'CREATE' | 'UPDATE' | 'DELETE' | 'LOGIN' | 'LOGOUT' | 'BOOKING_CREATED' | 'BOOKING_CANCELLED' | 'PAYMENT_COMPLETED';

// ============================================
// User Types
// ============================================

export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: UserRole;
  phoneNumber?: string | null;
  profileImage?: string | null;
  emailVerified: boolean;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface UserWithCourses extends User {
  instructorCourses?: Course[];
  bookings?: Booking[];
}

export interface CreateUserInput {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  role?: UserRole;
  phoneNumber?: string;
}

// ============================================
// Course Types
// ============================================

export interface Course {
  id: string;
  title: string;
  description: string;
  shortDescription?: string | null;
  category: string;
  level: string;
  thumbnail?: string | null;
  price: number;
  duration: number;
  maxStudents: number;
  instructorId: string;
  prerequisites?: string | null;
  learningOutcomes?: string | null;
  syllabus?: string | null;
  isPublished: boolean;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface CourseWithInstructor extends Course {
  instructor: User;
  _count?: {
    sessions: number;
    bookings: number;
  };
}

export interface CourseWithDetails extends CourseWithInstructor {
  sessions?: Session[];
  availableSeats?: number;
}

export interface CreateCourseInput {
  title: string;
  description: string;
  shortDescription?: string;
  category: string;
  level: string;
  thumbnail?: string;
  price: number;
  duration: number;
  maxStudents?: number;
  instructorId: string;
  prerequisites?: string;
  learningOutcomes?: string;
  syllabus?: string;
  isPublished?: boolean;
}

export interface UpdateCourseInput extends Partial<CreateCourseInput> {
  id: string;
}

// ============================================
// Session Types
// ============================================

export interface Session {
  id: string;
  courseId: string;
  title: string;
  description?: string | null;
  sessionDate: Date;
  startTime: Date;
  endTime: Date;
  location?: string | null;
  meetingLink?: string | null;
  maxStudents: number;
  status: SessionStatus;
  createdAt: Date;
  updatedAt: Date;
}

export interface SessionWithCourse extends Session {
  course: Course;
  _count?: {
    bookings: number;
  };
}

export interface CreateSessionInput {
  courseId: string;
  title: string;
  description?: string;
  sessionDate: Date;
  startTime: Date;
  endTime: Date;
  location?: string;
  meetingLink?: string;
  maxStudents?: number;
}

// ============================================
// Booking Types
// ============================================

export interface Booking {
  id: string;
  bookingReference: string;
  studentId: string;
  courseId: string;
  sessionId: string;
  status: BookingStatus;
  numberOfSeats: number;
  totalAmount: number;
  cancellationDate?: Date | null;
  cancellationReason?: string | null;
  attended: boolean;
  attendanceMarkedAt?: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface BookingWithDetails extends Booking {
  student: User;
  course: Course;
  session: Session;
  payments?: Payment[];
}

export interface CreateBookingInput {
  studentId: string;
  courseId: string;
  sessionId: string;
  numberOfSeats?: number;
  totalAmount: number;
}

// ============================================
// Waitlist Types
// ============================================

export interface Waitlist {
  id: string;
  studentId: string;
  courseId: string;
  status: WaitlistStatus;
  position: number;
  notifiedAt?: Date | null;
  expiresAt?: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface WaitlistWithDetails extends Waitlist {
  student: User;
  course: Course;
}

// ============================================
// Payment Types
// ============================================

export interface Payment {
  id: string;
  transactionId: string;
  studentId: string;
  bookingId: string;
  amount: number;
  currency: string;
  status: PaymentStatus;
  paymentMethod: PaymentMethod;
  gatewayResponse?: string | null;
  gatewayReference?: string | null;
  refundAmount?: number | null;
  refundReason?: string | null;
  refundedAt?: Date | null;
  paidAt?: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreatePaymentInput {
  studentId: string;
  bookingId: string;
  amount: number;
  currency?: string;
  paymentMethod: PaymentMethod;
  gatewayReference?: string;
}

// ============================================
// Certificate Types
// ============================================

export interface Certificate {
  id: string;
  certificateNumber: string;
  studentId: string;
  courseId: string;
  issueDate: Date;
  expiryDate?: Date | null;
  certificateUrl?: string | null;
  isValid: boolean;
  verificationCode: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface CertificateWithDetails extends Certificate {
  student: User;
  course: Course;
}

// ============================================
// Audit Types
// ============================================

export interface Audit {
  id: string;
  userId?: string | null;
  action: AuditAction;
  entityType: string;
  entityId?: string | null;
  metadata?: Record<string, unknown> | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  timestamp: Date;
}

// ============================================
// API Response Types
// ============================================

export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

export interface PaginatedResponse<T> extends ApiResponse<T[]> {
  pagination?: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

// ============================================
// Filter & Query Types
// ============================================

export interface CourseFilters {
  search?: string;
  category?: string;
  level?: string;
  minPrice?: number;
  maxPrice?: number;
  instructorId?: string;
  isPublished?: boolean;
}

export interface PaginationParams {
  page?: number;
  limit?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

// ============================================
// Auth Types (Placeholder for NextAuth)
// ============================================

export interface SessionUser {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: UserRole;
  profileImage?: string | null;
}

export interface AuthSession {
  user: SessionUser;
  expires: string;
}
